name: sonar-scan
description: "Run SonarQube/SonarCloud analysis (requires SONAR_HOST_URL and SONAR_TOKEN)."
inputs:
  project-key:
    required: true
  project-name:
    required: false
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Java (sonar-scanner requirement)
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Download sonar-scanner
      shell: bash
      run: |
        set -euo pipefail
        SCANNER_DIR="${RUNNER_TEMP}/sonar-scanner"
        mkdir -p "$SCANNER_DIR"
        # minimal approach: use sonar-scanner-cli if available via apt or download
        # try apt first (may not be available on all runners)
        if command -v sonar-scanner >/dev/null 2>&1; then
          echo "sonar-scanner already installed"
        else
          wget -q -O - "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip" > /tmp/sonar.zip
          apt-get update && apt-get install -y unzip >/dev/null
          unzip -q /tmp/sonar.zip -d /opt
          export PATH="/opt/sonar-scanner-*/bin:$PATH"
        fi

    - name: Run sonar-scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      shell: bash
      run: |
        set -euo pipefail
        if [[ -z "${SONAR_TOKEN:-}" || -z "${SONAR_HOST_URL:-}" ]]; then
          echo "SONAR_TOKEN or SONAR_HOST_URL not provided; skipping sonar."
          exit 0
        fi
        sonar-scanner \
          -Dsonar.projectKey="${{ inputs.project-key }}" \
          -Dsonar.host.url="${SONAR_HOST_URL}" \
          -Dsonar.login="${SONAR_TOKEN}" \
          -Dsonar.projectName="${{ inputs.project-name }}"
