policies:
- id: require-audit
  effect: require
  requirement: audit
- id: no-prod-write
  effect: deny
  condition: context.environment == "prod" && request.action in ["write","deploy"]
- id: hitl-required
  effect: require
  requirement: hitl
