id: sdlc.cicd.pipeline_hardening
name: Pipeline Hardening
intent: sdlc.cicd
domain: sdlc
description: 'Harden pipelines: signatures, provenance, approvals, gates.'
risk:
  level: high
  data_sensitivity: internal
allowed_channels:
- ide
- chat
- pipeline
providers:
- github_copilot
- azure_foundry
- agent_skill
default_provider:
  ide: github_copilot
  batch: agent_skill
tools_allowed:
- github.read_repo
- github.read_pr
- github.comment_pr
governance:
  audit: required
  hitl: true
  max_tokens: 6000
