name: reusable-ci-security-build-deploy

on:
  workflow_call:
    inputs:
      app_name:
        type: string
        required: false
        default: ""
      app_version:
        type: string
        required: false
        default: "" # si viene vacío, se intenta inferir en "prep"
      tech:
        type: string
        required: false
        default: "" # python|typescript|kotlin|swift|java|dotnet|go|node
      runner:
        type: string
        required: false
        default: "ubuntu-latest" # permitir override a macos-latest para iOS/Swift si aplica
      build_cmd:
        type: string
        required: false
        default: "echo 'TODO: build'"
      deploy_cmd:
        type: string
        required: false
        default: "echo 'TODO: deploy'"
      run_deploy:
        type: boolean
        required: false
        default: false
      sonar_project_key:
        type: string
        required: false
        default: ""
      snyk_fail_on:
        type: string
        required: false
        default: "high" # low|medium|high|all
    secrets:
      SONAR_TOKEN:
        required: false
      SONAR_HOST_URL:
        required: false
      SNYK_TOKEN:
        required: false
      DEPLOY_TOKEN:
        required: false

permissions:
  contents: read

jobs:
  prep:
    name: prep
    runs-on: ${{ inputs.runner }}
    outputs:
      app_name: ${{ steps.meta.outputs.app_name }}
      app_version: ${{ steps.meta.outputs.app_version }}
      actor: ${{ steps.meta.outputs.actor }}
      repo: ${{ steps.meta.outputs.repo }}
      sha: ${{ steps.meta.outputs.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Analyze + common metadata
        id: meta
        shell: bash
        run: |
          set -euo pipefail

          # --- app_name ---
          APP_NAME="${{ inputs.app_name }}"
          if [[ -z "$APP_NAME" ]]; then
            APP_NAME="${GITHUB_REPOSITORY##*/}"
          fi

          # --- app_version ---
          APP_VERSION="${{ inputs.app_version }}"
          if [[ -z "$APP_VERSION" ]]; then
            if [[ -f package.json ]]; then
              APP_VERSION="$(node -p "require('./package.json').version")"
            elif [[ -f pom.xml ]]; then
              APP_VERSION="$(grep -m1 -oP '(?<=<version>)[^<]+' pom.xml || true)"
            elif [[ -f pyproject.toml ]]; then
              APP_VERSION="$(grep -m1 -E '^version *= *' pyproject.toml | sed -E "s/.*= *\"?([^\"]+)\"?/\1/" || true)"
            elif [[ -f build.gradle ]] || [[ -f build.gradle.kts ]]; then
              APP_VERSION="$(grep -m1 -E 'version *= *' build.gradle* | sed -E "s/.*= *[\"']?([^\"']+)[\"']?/\1/" || true)"
            elif [[ -f Package.swift ]]; then
              APP_VERSION=""
            fi

            if [[ -z "$APP_VERSION" ]]; then
              APP_VERSION="${GITHUB_SHA::7}"
            fi
          fi

          echo "app_name=$APP_NAME" >> "$GITHUB_OUTPUT"
          echo "app_version=$APP_VERSION" >> "$GITHUB_OUTPUT"
          echo "actor=$GITHUB_ACTOR" >> "$GITHUB_OUTPUT"
          echo "repo=$GITHUB_REPOSITORY" >> "$GITHUB_OUTPUT"
          echo "sha=$GITHUB_SHA" >> "$GITHUB_OUTPUT"

  build:
    name: build
    runs-on: ${{ inputs.runner }}
    needs: [prep]
    steps:
      - uses: actions/checkout@v4

      - name: Resolve build command by tech
        id: resolve_build
        shell: bash
        run: |
          set -euo pipefail
          USER_CMD=${{ toJson(inputs.build_cmd) }}
          USER_CMD="${USER_CMD%\"}"; USER_CMD="${USER_CMD#\"}"

          if [[ "$USER_CMD" != "echo 'TODO: build'" && -n "$USER_CMD" ]]; then
            echo "cmd=$USER_CMD" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          TECH="$(echo "${{ inputs.tech }}" | tr '[:upper:]' '[:lower:]')"
          case "$TECH" in
            typescript|node|javascript)
              echo "cmd=npm ci && npm run build" >> "$GITHUB_OUTPUT"
              ;;
            python)
              echo "cmd=pip install -U pip setuptools wheel && \
                      if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi && \
                      pytest -q || true && \
                      echo 'python build step (ajusta según tu proyecto)'" >> "$GITHUB_OUTPUT"
              ;;
            kotlin|java|gradle)
              echo "cmd=./gradlew --no-daemon build" >> "$GITHUB_OUTPUT"
              ;;
            swift)
              echo "cmd=swift build -c release" >> "$GITHUB_OUTPUT"
              ;;
            dotnet)
              echo "cmd=dotnet restore && dotnet build --configuration Release && dotnet test --no-build" >> "$GITHUB_OUTPUT"
              ;;
            go)
              echo "cmd=go mod download && go build ./... && go test ./..." >> "$GITHUB_OUTPUT"
              ;;
            *)
              echo "cmd=echo 'TODO: build (define build_cmd o tech)'" >> "$GITHUB_OUTPUT"
              ;;
          esac

      - name: Build
        shell: bash
        run: |
          set -euo pipefail
          ${{ steps.resolve_build.outputs.cmd }}

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: build-output
      #     path: dist

  sonar:
    name: static-scan-sonar
    runs-on: ${{ inputs.runner }}
    needs: [prep, build]
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - name: Sonar (placeholder)
        shell: bash
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_PROJECT_KEY: ${{ inputs.sonar_project_key }}
        run: |
          set -euo pipefail
          if [[ -z "${SONAR_TOKEN:-}" || -z "${SONAR_HOST_URL:-}" || -z "${SONAR_PROJECT_KEY:-}" ]]; then
            echo "Sonar: faltan SONAR_TOKEN / SONAR_HOST_URL / sonar_project_key. Skipping."
            exit 0
          fi

          # TODO: sonar-scanner real aquí
          echo "TODO: sonar scan here"

  snyk:
    name: static-scan-snyk
    runs-on: ${{ inputs.runner }}
    needs: [prep, build]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Snyk CLI
        if: ${{ secrets.SNYK_TOKEN != '' }}
        uses: snyk/actions/setup@v2
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Snyk test
        if: ${{ secrets.SNYK_TOKEN != '' }}
        shell: bash
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          set -euo pipefail
          snyk test --all --fail-on=${{ inputs.snyk_fail_on }}

      - name: Snyk monitor
        if: ${{ secrets.SNYK_TOKEN != '' }}
        shell: bash
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: |
          set -euo pipefail
          snyk monitor --all --project-name="${{ needs.prep.outputs.app_name }}" --project-tags="version=${{ needs.prep.outputs.app_version }}"

      - name: Snyk missing token
        if: ${{ secrets.SNYK_TOKEN == '' }}
        run: echo "SNYK_TOKEN no configurado. Skipping."

  deploy:
    name: deploy
    runs-on: ${{ inputs.runner }}
    needs: [prep, build, sonar, snyk]
    if: ${{ inputs.run_deploy }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      # - uses: actions/download-artifact@v4
      #   with:
      #     name: build-output
      #     path: dist

      - name: Resolve deploy command
        id: resolve_deploy
        shell: bash
        run: |
          set -euo pipefail
          USER_CMD=${{ toJson(inputs.deploy_cmd) }}
          USER_CMD="${USER_CMD%\"}"; USER_CMD="${USER_CMD#\"}"
          if [[ -n "$USER_CMD" && "$USER_CMD" != "echo 'TODO: deploy'" ]]; then
            echo "cmd=$USER_CMD" >> "$GITHUB_OUTPUT"
          else
            echo "cmd=echo 'TODO: deploy (define deploy_cmd según tu plataforma)'" >> "$GITHUB_OUTPUT"
          fi

      - name: Deploy
        shell: bash
        env:
          DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          APP_NAME: ${{ needs.prep.outputs.app_name }}
          APP_VERSION: ${{ needs.prep.outputs.app_version }}
        run: |
          set -euo pipefail
          if [[ -z "${DEPLOY_TOKEN:-}" ]]; then
            echo "DEPLOY_TOKEN no configurado. Skipping deploy."
            exit 0
          fi
          ${{ steps.resolve_deploy.outputs.cmd }}