snyk:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
    - uses: snyk/actions/setup@v4
    - name: Auth Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}
    - name: Snyk Open Source (SCA) → SARIF
      continue-on-error: true
      run: snyk test --all-projects --sarif-file-output=snyk-sca.sarif
    - name: Snyk Code (SAST) → SARIF
      continue-on-error: true
      run: snyk code test --sarif-file-output=snyk-code.sarif
    - name: Upload SARIF
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: .